### ISSUE TITLE
Does not work?

### ISSUE THREAD

**Issue by henrikra** [yayoc/optional-chain#1]
There are couple mistakes in the example in the README so here is my code:

```
interface User {
  name?: {
    first: string
  },
}

const user: User = { name: undefined };
const optionalUser = optional(user);
optionalUser.k("name").k("first").get();
```

![image](https://user-images.githubusercontent.com/12229968/42128850-84ffe54e-7cbd-11e8-9c26-b5bb48b44e0f.png)

But I am getting error `[ts] Argument of type '"first"' is not assignable to parameter of type 'never'.` on `firstName`

So what I am doing wrong? 🤔

**Comment by yayoc** [comment]
@henrikra 
Yes, You are correct. `v0.1.0` was not handling optional properties properly.
I published [v0.1.1](https://github.com/yayoc/optional-chain/releases/tag/v0.1.1) to solve the issue.
Thanks.
